### ISSUE TITLE
Failed to load the change-case package

### ISSUE THREAD

**Issue by tjbenton** [robhurring/atom-change-case#32]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [change-case](https://github.com/robhurring/atom-change-case) package, v0.6.3

### Stack Trace

Failed to load the change-case package

```
At Cannot find module 'no-case'

Error: Cannot find module 'no-case'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/tylerbenton/.atom/packages/change-case/node_modules/change-case/change-case.js:1:110)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/tylerbenton/.atom/packages/change-case/lib/change-case.coffee:1:14)
    at Object.<anonymous> (/Users/tylerbenton/.atom/packages/change-case/lib/change-case.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "es-navigation",
      "terminal-status",
      "highlight-selected",
      "git-diff-details",
      "language-javascript-jsx",
      "jscs-fixer",
      "linter-jscs",
      "linter-jshint",
      "Stylus",
      "linter-stylint",
      "hyperclick"
    ],
    "ignoredNames": [
      ".git",
      ".sass-cache/",
      ".DS_Store",
      ".subl*.tmp",
      "desktop/"
    ],
    "themes": [
      "atom-material-ui",
      "oceanic-next"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
Sublime-Style-Column-Selection, v1.6.0
angularjs, v0.3.5
atom-beautify, vundefined
atom-jade, v0.3.0
atom-material-ui, v1.3.3
atom-pair, v2.0.10
auto-update-packages, v1.0.1
change-case, v0.6.3
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.17
fold-functions, v0.4.3
language-SCSS, v0.4.0
language-babel, vundefined
language-cfml, v0.14.0
language-html-swig, v2.0.1
language-swig-wrapper, v0.2.0
linter, v1.11.14
linter-eslint, v7.2.4
linter-scss-lint, v3.0.4
linter-stylelint, v3.0.2
merge-conflicts, v1.4.4
my-language-stylus, v1.2.1
oceanic-next, v0.1.2
pigments, vundefined
preview-plus, v1.2.7
react, v0.15.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by deiga** [comment]
I can't seem to be able to reproduce this, is this still an issue?

**Comment by tjbenton** [comment]
I just uninstalled it and reinstalled it and that seemed to fix the problem.
